rule GenerateIndex:
    input:
        GENOME
    output:
        directory(path.join(STAR_DIR, "index"))
    params:
        partition = "main",
        nodes = "1",
        ntasks = "6",
        time = "02:00:00",
        mem = "36G",
        mail_user = EMAIL,
        mail_type = EMAIL_TYPE
    log:
        path.join(STAR_DIR, "logs", "index", "star_index.log")
    conda:
        "envs/star.yml"
    script:
        "scripts/star_index.py"

rule StarAlign:
    input:
        star_idx = get_star_idx,
        reads = get_reads
    output:
        path.join(STAR_DIR, "alignments", "{sample}", "Aligned.sortedByCoord.out.bam")
    params:
        partition = "main",
        nodes = "1",
        ntasks = "6",
        time = "3:00:00",
        mem = "36G",
        mail_user = EMAIL,
        mail_type = EMAIL_TYPE
    log:
        path.join(STAR_DIR, "logs", "alignment", "{sample}_alignment.log")
    conda:
        "envs/star.yml"
    script:
        "scripts/star_align.py"
