rule OverlapAll:
    input:
        miso = path.join(MISO_COMP_DIR, "{comparison}", "{comparison}.merged.w_coord.miso_bf"),
        rmats = path.join(RMATS_DIR, "results", "{comparison}", "{comparison}.merged.w_coord.tsv"),
        whippet = path.join(WHIPPET_DIR, "delta", "{comparison}", "{comparison}.diff.gz")
    output:
        path.join(RESULT_DIR, "{comparison}", "overlap.all_tools.tab")
    params:
        partition = "main",
        nodes = "1",
        ntasks = "4",
        time = "00:20:00",
        mem = "8G",
        mail_user = EMAIL,
        mail_type = EMAIL_TYPE
    script:
        "scripts/overlap.py"
